/**
 * Legal Metadata for 77 Pending Tax Indexes (ZH 2024)
 * Based on Swiss Federal Tax Law (DBG) and Zurich Cantonal Tax Law (StG ZH)
 *
 * Each index includes:
 * - Legal_Reference_Canton: Zurich cantonal law reference (§ StG ZH)
 * - Legal_Reference_Federal: Swiss federal law reference (Art. DBG)
 * - Rational_Explanation: Detailed explanation in German
 * - Deductibility_Rules: Tax treatment rules
 * - Max_Deductible: Maximum amounts / limits
 * - Limitations: Documentation requirements
 */

const legalMetadata = {
  // INCOME INDEXES (100-199)

  // Employment Income (100-103)
  "100": {
    Canton: "ZH",
    Index: "100",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Unselbständige Erwerbstätigkeit",
    Person: "Person 1",
    Description: "Main employment Person 1",
    Legal_Reference_Canton: "§ 17 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 17 Abs. 1 DBG",
    Rational_Explanation: "Der Bruttolohn aus dem Haupterwerb umfasst alle Einkünfte aus unselbständiger Erwerbstätigkeit gemäss Lohnausweis. Dies beinhaltet den regulären Lohn sowie sämtliche Nebeneinkünfte wie Gratifikationen, Boni, Provisionen, Zulagen, Naturalleistungen und geldwerte Vorteile aus dem Arbeitsverhältnis.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. Der Bruttolohn gemäss Lohnausweis ist ohne Abzüge als Einkommen zu deklarieren.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Lohnausweis des Arbeitgebers erforderlich. Der deklarierte Betrag muss mit dem Lohnausweis übereinstimmen. Pauschalabzug für Berufsauslagen separat unter Ziffer 11 (3% des Nettolohns, min. CHF 2'000, max. CHF 4'000).",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 8, Ziffer 1.1",
    Verification_Status: "verified"
  },

  "101": {
    Canton: "ZH",
    Index: "101",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Unselbständige Erwerbstätigkeit",
    Person: "Person 2",
    Description: "Main employment Person 2",
    Legal_Reference_Canton: "§ 17 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 17 Abs. 1 DBG",
    Rational_Explanation: "Der Bruttolohn aus dem Haupterwerb der zweiten Person umfasst alle Einkünfte aus unselbständiger Erwerbstätigkeit gemäss Lohnausweis. Dies beinhaltet den regulären Lohn sowie sämtliche Nebeneinkünfte wie Gratifikationen, Boni, Provisionen, Zulagen, Naturalleistungen und geldwerte Vorteile aus dem Arbeitsverhältnis.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. Der Bruttolohn gemäss Lohnausweis ist ohne Abzüge als Einkommen zu deklarieren.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Lohnausweis des Arbeitgebers erforderlich. Der deklarierte Betrag muss mit dem Lohnausweis übereinstimmen. Pauschalabzug für Berufsauslagen separat unter Ziffer 12 (3% des Nettolohns, min. CHF 2'000, max. CHF 4'000).",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 8, Ziffer 1.1",
    Verification_Status: "verified"
  },

  "102": {
    Canton: "ZH",
    Index: "102",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Unselbständige Erwerbstätigkeit",
    Person: "Person 1",
    Description: "Secondary employment Person 1",
    Legal_Reference_Canton: "§ 17 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 17 Abs. 1 DBG",
    Rational_Explanation: "Einkünfte aus Nebenerwerb (zusätzliche Arbeitsverhältnisse neben dem Haupterwerb) sind vollumfänglich steuerbar. Dies umfasst alle Einkünfte aus zweiten oder weiteren Arbeitsverhältnissen, Mandaten, Verwaltungsräten oder nebenberuflichen Tätigkeiten gemäss separatem Lohnausweis.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. Alle Nebenerwerbs-Einkünfte sind ohne Abzüge als Einkommen zu deklarieren.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Lohnausweis oder Honorarbestätigung erforderlich. Bei Verwaltungsratsmandaten: Honorarbestätigung der Gesellschaft. Pauschalabzug für Berufsauslagen separat unter Ziffer 11.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 8, Ziffer 1.2",
    Verification_Status: "verified"
  },

  "103": {
    Canton: "ZH",
    Index: "103",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Unselbständige Erwerbstätigkeit",
    Person: "Person 2",
    Description: "Secondary employment Person 2",
    Legal_Reference_Canton: "§ 17 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 17 Abs. 1 DBG",
    Rational_Explanation: "Einkünfte aus Nebenerwerb der zweiten Person (zusätzliche Arbeitsverhältnisse neben dem Haupterwerb) sind vollumfänglich steuerbar. Dies umfasst alle Einkünfte aus zweiten oder weiteren Arbeitsverhältnissen, Mandaten, Verwaltungsräten oder nebenberuflichen Tätigkeiten gemäss separatem Lohnausweis.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. Alle Nebenerwerbs-Einkünfte sind ohne Abzüge als Einkommen zu deklarieren.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Lohnausweis oder Honorarbestätigung erforderlich. Bei Verwaltungsratsmandaten: Honorarbestätigung der Gesellschaft. Pauschalabzug für Berufsauslagen separat unter Ziffer 12.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 8, Ziffer 1.2",
    Verification_Status: "verified"
  },

  // Self-Employment Income (120-123)
  "120": {
    Canton: "ZH",
    Index: "120",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Selbständige Erwerbstätigkeit",
    Person: "Person 1",
    Description: "Main self-employment Person 1",
    Legal_Reference_Canton: "§ 18 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 18 Abs. 1 DBG",
    Rational_Explanation: "Einkünfte aus selbständiger Erwerbstätigkeit umfassen den Reingewinn aus Geschäftstätigkeit (Einzelfirma, Personengesellschaft). Dies ist der Überschuss der Geschäftseinnahmen über die Geschäftsausgaben gemäss Jahresrechnung. Die Gewinnermittlung erfolgt über Hilfsblatt A.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. Berechnung: Geschäftsertrag minus geschäftsmässig begründete Aufwendungen gemäss Geschäftsbuchhaltung.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Hilfsblatt A (Gewinnermittlung) ausfüllen erforderlich. Jahresrechnung mit Erfolgsrechnung und Bilanz. Bei erstmaliger selbständiger Tätigkeit: Nachweis der Geschäftseröffnung. AHV-Abrechnung für Selbständigerwerbende.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 9, Ziffer 2.1; Hilfsblatt A",
    Verification_Status: "verified"
  },

  "121": {
    Canton: "ZH",
    Index: "121",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Selbständige Erwerbstätigkeit",
    Person: "Person 2",
    Description: "Main self-employment Person 2",
    Legal_Reference_Canton: "§ 18 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 18 Abs. 1 DBG",
    Rational_Explanation: "Einkünfte aus selbständiger Erwerbstätigkeit der zweiten Person umfassen den Reingewinn aus Geschäftstätigkeit (Einzelfirma, Personengesellschaft). Dies ist der Überschuss der Geschäftseinnahmen über die Geschäftsausgaben gemäss Jahresrechnung. Die Gewinnermittlung erfolgt über Hilfsblatt A.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. Berechnung: Geschäftsertrag minus geschäftsmässig begründete Aufwendungen gemäss Geschäftsbuchhaltung.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Hilfsblatt A (Gewinnermittlung) ausfüllen erforderlich. Jahresrechnung mit Erfolgsrechnung und Bilanz. Bei erstmaliger selbständiger Tätigkeit: Nachweis der Geschäftseröffnung. AHV-Abrechnung für Selbständigerwerbende.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 9, Ziffer 2.1; Hilfsblatt A",
    Verification_Status: "verified"
  },

  "122": {
    Canton: "ZH",
    Index: "122",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Selbständige Erwerbstätigkeit",
    Person: "Person 1",
    Description: "Secondary self-employment Person 1",
    Legal_Reference_Canton: "§ 18 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 18 Abs. 1 DBG",
    Rational_Explanation: "Einkünfte aus nebenberuflicher selbständiger Tätigkeit (z.B. Nebenerwerb als Berater, Freelancer) sind vollumfänglich steuerbar. Dies umfasst den Reingewinn aus nebenberuflicher Geschäftstätigkeit, die zusätzlich zur Haupttätigkeit ausgeübt wird.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. Berechnung: Geschäftsertrag aus Nebenerwerb minus direkt zurechenbare Geschäftsaufwendungen.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Hilfsblatt A ausfüllen oder vereinfachte Gewinnermittlung bei kleineren Beträgen. Belege für Einnahmen und Ausgaben erforderlich. Bei AHV-pflichtiger Tätigkeit: AHV-Abrechnung.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 9, Ziffer 2.2",
    Verification_Status: "verified"
  },

  "123": {
    Canton: "ZH",
    Index: "123",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Selbständige Erwerbstätigkeit",
    Person: "Person 2",
    Description: "Secondary self-employment Person 2",
    Legal_Reference_Canton: "§ 18 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 18 Abs. 1 DBG",
    Rational_Explanation: "Einkünfte aus nebenberuflicher selbständiger Tätigkeit der zweiten Person (z.B. Nebenerwerb als Berater, Freelancer) sind vollumfänglich steuerbar. Dies umfasst den Reingewinn aus nebenberuflicher Geschäftstätigkeit, die zusätzlich zur Haupttätigkeit ausgeübt wird.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. Berechnung: Geschäftsertrag aus Nebenerwerb minus direkt zurechenbare Geschäftsaufwendungen.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Hilfsblatt A ausfüllen oder vereinfachte Gewinnermittlung bei kleineren Beträgen. Belege für Einnahmen und Ausgaben erforderlich. Bei AHV-pflichtiger Tätigkeit: AHV-Abrechnung.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 9, Ziffer 2.2",
    Verification_Status: "verified"
  },

  // AHV/IV Pensions (130-131)
  "130": {
    Canton: "ZH",
    Index: "130",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Vorsorge",
    Person: "Person 1",
    Description: "AHV/IV pensions Person 1",
    Legal_Reference_Canton: "§ 22 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 22 Abs. 1 DBG",
    Rational_Explanation: "AHV-Renten (Alters- und Hinterlassenenversicherung) und IV-Renten (Invalidenversicherung) sind vollumfänglich als Einkommen steuerbar. Dies umfasst ordentliche AHV-Renten, Witwen-/Witwerrenten, Waisenrenten und IV-Renten aller Stufen.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. AHV- und IV-Renten werden wie Erwerbseinkommen behandelt und zum vollen Betrag als Einkommen erfasst.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Rentenausweis der AHV/IV-Kasse erforderlich. Jahresabrechnung oder Verfügung der Ausgleichskasse. Bei ausländischen Sozialversicherungsrenten: Bestätigung der ausländischen Institution, Umrechnung in CHF.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 10, Ziffer 3.1",
    Verification_Status: "verified"
  },

  "131": {
    Canton: "ZH",
    Index: "131",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Vorsorge",
    Person: "Person 2",
    Description: "AHV/IV pensions Person 2",
    Legal_Reference_Canton: "§ 22 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 22 Abs. 1 DBG",
    Rational_Explanation: "AHV-Renten (Alters- und Hinterlassenenversicherung) und IV-Renten (Invalidenversicherung) der zweiten Person sind vollumfänglich als Einkommen steuerbar. Dies umfasst ordentliche AHV-Renten, Witwen-/Witwerrenten, Waisenrenten und IV-Renten aller Stufen.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. AHV- und IV-Renten werden wie Erwerbseinkommen behandelt und zum vollen Betrag als Einkommen erfasst.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Rentenausweis der AHV/IV-Kasse erforderlich. Jahresabrechnung oder Verfügung der Ausgleichskasse. Bei ausländischen Sozialversicherungsrenten: Bestätigung der ausländischen Institution, Umrechnung in CHF.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 10, Ziffer 3.1",
    Verification_Status: "verified"
  },

  // Other Pensions (134-137)
  "134": {
    Canton: "ZH",
    Index: "134",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Vorsorge",
    Person: "Person 1",
    Description: "Occupational pension (2nd pillar) Person 1",
    Legal_Reference_Canton: "§ 22 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 22 Abs. 1 lit. a DBG",
    Rational_Explanation: "Renten aus beruflicher Vorsorge (Pensionskasse, 2. Säule) sind vollumfänglich als Einkommen steuerbar. Dies umfasst Altersrenten, Invalidenrenten, Witwen-/Witwerrenten und Waisenrenten aus der Pensionskasse sowie aus Freizügigkeitspolicen.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. Pensionskassenrenten werden als periodisches Einkommen erfasst und zum normalen Tarif besteuert.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Rentenausweis der Pensionskasse erforderlich. Jahresabrechnung mit Angabe der Rentenhöhe. WICHTIG: Kapitalleistungen aus 2. Säule werden separat unter Ziffer 26 (Index 510) zu privilegiertem Sondersatz besteuert.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 10, Ziffer 3.2",
    Verification_Status: "verified"
  },

  "135": {
    Canton: "ZH",
    Index: "135",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Vorsorge",
    Person: "Person 2",
    Description: "Occupational pension (2nd pillar) Person 2",
    Legal_Reference_Canton: "§ 22 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 22 Abs. 1 lit. a DBG",
    Rational_Explanation: "Renten aus beruflicher Vorsorge (Pensionskasse, 2. Säule) der zweiten Person sind vollumfänglich als Einkommen steuerbar. Dies umfasst Altersrenten, Invalidenrenten, Witwen-/Witwerrenten und Waisenrenten aus der Pensionskasse sowie aus Freizügigkeitspolicen.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. Pensionskassenrenten werden als periodisches Einkommen erfasst und zum normalen Tarif besteuert.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Rentenausweis der Pensionskasse erforderlich. Jahresabrechnung mit Angabe der Rentenhöhe. WICHTIG: Kapitalleistungen aus 2. Säule werden separat unter Ziffer 26 (Index 510) zu privilegiertem Sondersatz besteuert.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 10, Ziffer 3.2",
    Verification_Status: "verified"
  },

  "136": {
    Canton: "ZH",
    Index: "136",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Vorsorge",
    Person: "Person 1",
    Description: "Other pensions and annuities Person 1",
    Legal_Reference_Canton: "§ 22 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 22 Abs. 1 lit. b DBG",
    Rational_Explanation: "Übrige Renten und wiederkehrende Leistungen (z.B. private Rentenversicherungen, Leibrenten, ausländische Renten) sind steuerbar. Leibrenten werden zu 40% besteuert (Ertragsanteil), übrige wiederkehrende Leistungen zu 100%.",
    Deductibility_Rules: "Leibrenten: 40% steuerbar (Ertragsanteil). Übrige wiederkehrende Leistungen: 100% steuerbar. Berechnung gemäss Art der Rentenzahlung.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Rentenvertrag oder Versicherungspolice erforderlich. Bei Leibrenten: Nachweis des Rententyps (40%-Regel). Bei ausländischen Renten: Bestätigung der Institution, Umrechnung in CHF, DBA-Status prüfen.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 10-11, Ziffer 3.5",
    Verification_Status: "verified"
  },

  "137": {
    Canton: "ZH",
    Index: "137",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Vorsorge",
    Person: "Person 2",
    Description: "Other pensions and annuities Person 2",
    Legal_Reference_Canton: "§ 22 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 22 Abs. 1 lit. b DBG",
    Rational_Explanation: "Übrige Renten und wiederkehrende Leistungen der zweiten Person (z.B. private Rentenversicherungen, Leibrenten, ausländische Renten) sind steuerbar. Leibrenten werden zu 40% besteuert (Ertragsanteil), übrige wiederkehrende Leistungen zu 100%.",
    Deductibility_Rules: "Leibrenten: 40% steuerbar (Ertragsanteil). Übrige wiederkehrende Leistungen: 100% steuerbar. Berechnung gemäss Art der Rentenzahlung.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Rentenvertrag oder Versicherungspolice erforderlich. Bei Leibrenten: Nachweis des Rententyps (40%-Regel). Bei ausländischen Renten: Bestätigung der Institution, Umrechnung in CHF, DBA-Status prüfen.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 10-11, Ziffer 3.5",
    Verification_Status: "verified"
  },

  // Unemployment and Family Allowances (140-143)
  "140": {
    Canton: "ZH",
    Index: "140",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Ersatzeinkommen",
    Person: "Person 1",
    Description: "Unemployment benefits Person 1",
    Legal_Reference_Canton: "§ 22 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 23 lit. a DBG",
    Rational_Explanation: "Arbeitslosenentschädigungen (Taggelder der Arbeitslosenversicherung) sind als Erwerbsersatzeinkommen vollumfänglich steuerbar. Dies umfasst Leistungen bei Arbeitslosigkeit, Kurzarbeit, Schlechtwetter sowie Insolvenzentschädigungen.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. Arbeitslosenentschädigungen werden wie Erwerbseinkommen behandelt und zum normalen Tarif besteuert.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Bescheinigung der Arbeitslosenkasse erforderlich. Jahresabrechnung mit Angabe der bezogenen Taggelder. Quellensteuerabzug wird in der Regel vorgenommen und muss bei der Veranlagung verrechnet werden.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 10, Ziffer 3.3",
    Verification_Status: "verified"
  },

  "141": {
    Canton: "ZH",
    Index: "141",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Ersatzeinkommen",
    Person: "Person 2",
    Description: "Unemployment benefits Person 2",
    Legal_Reference_Canton: "§ 22 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 23 lit. a DBG",
    Rational_Explanation: "Arbeitslosenentschädigungen der zweiten Person (Taggelder der Arbeitslosenversicherung) sind als Erwerbsersatzeinkommen vollumfänglich steuerbar. Dies umfasst Leistungen bei Arbeitslosigkeit, Kurzarbeit, Schlechtwetter sowie Insolvenzentschädigungen.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. Arbeitslosenentschädigungen werden wie Erwerbseinkommen behandelt und zum normalen Tarif besteuert.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Bescheinigung der Arbeitslosenkasse erforderlich. Jahresabrechnung mit Angabe der bezogenen Taggelder. Quellensteuerabzug wird in der Regel vorgenommen und muss bei der Veranlagung verrechnet werden.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 10, Ziffer 3.3",
    Verification_Status: "verified"
  },

  "142": {
    Canton: "ZH",
    Index: "142",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Ersatzeinkommen",
    Person: "Person 1",
    Description: "Other income replacement benefits Person 1",
    Legal_Reference_Canton: "§ 22 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 23 lit. b-c DBG",
    Rational_Explanation: "Weitere Erwerbsausfallentschädigungen (Mutterschafts-, Vaterschafts- und Betreuungsentschädigung, Militär- und Zivildienstsold, Corona-Erwerbsausfall) sind vollumfänglich steuerbar. Diese Leistungen ersetzen entgangenes Erwerbseinkommen.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. Alle Erwerbsersatzleistungen werden wie Erwerbseinkommen behandelt und zum normalen Tarif besteuert.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Bescheinigung der Ausgleichskasse (EO) erforderlich. Bei Militär/Zivildienst: Sold-Abrechnung. Bei Corona-Erwerbsausfall: Verfügung der zuständigen Behörde. Quellensteuerabzug muss verrechnet werden.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 11, Ziffer 3.4",
    Verification_Status: "verified"
  },

  "143": {
    Canton: "ZH",
    Index: "143",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Familienzulagen",
    Person: "",
    Description: "Family allowances",
    Legal_Reference_Canton: "§ 23 lit. g StG ZH",
    Legal_Reference_Federal: "Art. 24 lit. f bis DBG",
    Rational_Explanation: "Familienzulagen (Kinderzulagen, Ausbildungszulagen, Haushaltszulagen) sind grundsätzlich steuerfrei, ausser sie werden an Selbständigerwerbende ausbezahlt. Bei Selbständigen sind Familienzulagen vollumfänglich als Einkommen steuerbar.",
    Deductibility_Rules: "Bei unselbständig Erwerbenden: STEUERFREI (nicht deklarieren). Bei selbständig Erwerbenden: Vollumfänglich steuerbar zu 100%.",
    Max_Deductible: "Nicht zutreffend (bei Unselbständigen steuerfrei, bei Selbständigen Einkommensposition)",
    Limitations: "Nur für Selbständigerwerbende relevant. Bescheinigung der Familienausgleichskasse erforderlich. Bei unselbständig Erwerbenden bereits im Lohnausweis berücksichtigt (steuerfrei).",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 11, Ziffer 3.6",
    Verification_Status: "verified"
  },

  // Securities Income (150-151)
  "150": {
    Canton: "ZH",
    Index: "150",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Wertschriften und Guthaben",
    Person: "",
    Description: "Securities income (dividends, interest)",
    Legal_Reference_Canton: "§ 20 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 20 Abs. 1 lit. a-c DBG",
    Rational_Explanation: "Ertrag aus beweglichem Vermögen umfasst Dividenden aus Aktien, Zinsen aus Obligationen und Bankguthaben, Erträge aus Anlagefonds sowie übrige Kapitalerträge. Schweizer Dividenden sind nach Verrechnung der 35% Verrechnungssteuer steuerbar.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. Schweizer Dividenden: Bruttobetrag vor Verrechnungssteuer deklarieren (Verrechnungssteuer wird separat zurückerstattet). Zinsen: Bruttobetrag steuerbar.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Depotauszug oder Wertschriftenverzeichnis erforderlich. Dividendenabrechnungen, Zinsabrechnungen der Bank. Bei ausländischen Wertschriften: Quellensteuerbelege, Umrechnung in CHF, DBA-Status prüfen für Quellensteuerrückerstattung.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 12, Ziffer 4.1",
    Verification_Status: "verified"
  },

  "151": {
    Canton: "ZH",
    Index: "151",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Wertschriften und Guthaben",
    Person: "",
    Description: "Income from qualified participations (≥10%)",
    Legal_Reference_Canton: "§ 20 Abs. 1 lit. c StG ZH, § 20 Abs. 1 bis StG ZH",
    Legal_Reference_Federal: "Art. 20 Abs. 1 bis DBG",
    Rational_Explanation: "Dividenden aus qualifizierten Beteiligungen (mindestens 10% Kapital- oder Stimmrechtsanteil) werden privilegiert besteuert. Kantonal erfolgt eine Ermässigung um 50% des Durchschnittssatzes, Bund besteuert nur 70% des Betrags zum normalen Tarif.",
    Deductibility_Rules: "Privilegierte Besteuerung: Kantonal 50% Ermässigung, Bund 70% steuerbar. Beteiligung muss mindestens 10% des Grund- oder Stimmkapitals betragen.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition mit Privilegierung)",
    Limitations: "Aktienregisterauszug als Nachweis der 10%-Beteiligung erforderlich. Dividendenabrechnung. Separate Deklaration von normalen Dividenden (<10%) und qualifizierten Beteiligungen (≥10%). Verrechnungssteuerrückerstattung möglich.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 12, Ziffer 4.2; Merkblatt qualifizierte Beteiligungen",
    Verification_Status: "verified"
  },

  // Other Income (160-164)
  "160": {
    Canton: "ZH",
    Index: "160",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Übrige Einkünfte",
    Person: "",
    Description: "Alimony received (divorced/separated spouse)",
    Legal_Reference_Canton: "§ 23 lit. f StG ZH",
    Legal_Reference_Federal: "Art. 23 lit. f DBG",
    Rational_Explanation: "Erhaltene Unterhaltsbeiträge von geschiedenen oder getrennt lebenden Ehegatten/Partnern sind beim Empfänger vollumfänglich als Einkommen steuerbar. Dies gilt für periodische Zahlungen aufgrund Scheidungs-/Trennungsurteil oder Vereinbarung.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100% beim Empfänger. Beim Zahler unter Ziffer 13.1 (Index 254) abziehbar.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Scheidungs-/Trennungsurteil oder Unterhaltsvereinbarung erforderlich. Nachweis der erhaltenen Zahlungen (Banküberweisungen). WICHTIG: Nur periodische Zahlungen steuerbar, nicht einmalige Kapitalabfindungen.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 13, Ziffer 5.1",
    Verification_Status: "verified"
  },

  "161": {
    Canton: "ZH",
    Index: "161",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Übrige Einkünfte",
    Person: "",
    Description: "Child maintenance received (until majority)",
    Legal_Reference_Canton: "§ 23 lit. f StG ZH",
    Legal_Reference_Federal: "Art. 23 lit. f DBG",
    Rational_Explanation: "Erhaltene Kinderalimente (bis zum Monat der Volljährigkeit des Kindes) sind als Einkommen des Kindes steuerbar, werden aber beim empfangenden Elternteil deklariert. Nach Volljährigkeit erfolgt die Besteuerung direkt beim Kind.",
    Deductibility_Rules: "Vollumfänglich steuerbar als Einkommen des Kindes. Beim zahlenden Elternteil unter Ziffer 13.2 (Index 255) abziehbar.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition des Kindes)",
    Limitations: "Unterhaltsvereinbarung oder Gerichtsentscheid erforderlich. Nachweis der erhaltenen Zahlungen. Geburtsurkunde des Kindes. Bis Monat der Volljährigkeit (18. Altersjahr).",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 13, Ziffer 5.2",
    Verification_Status: "verified"
  },

  "162": {
    Canton: "ZH",
    Index: "162",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Übrige Einkünfte",
    Person: "",
    Description: "Income from partnerships and simple companies",
    Legal_Reference_Canton: "§ 23 lit. c StG ZH",
    Legal_Reference_Federal: "Art. 23 lit. c DBG",
    Rational_Explanation: "Einkünfte aus Beteiligungen an Personengesellschaften (Kollektiv-, Kommanditgesellschaften) und einfachen Gesellschaften sind anteilsmässig steuerbar. Der Gewinnanteil wird transparent beim Gesellschafter als Einkommen erfasst.",
    Deductibility_Rules: "Vollumfänglich steuerbar zu 100%. Besteuerung erfolgt beim Gesellschafter (Transparenzprinzip), nicht bei der Gesellschaft.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, kein Abzug)",
    Limitations: "Jahresrechnung der Gesellschaft erforderlich. Gewinnverteilungsschlüssel gemäss Gesellschaftsvertrag. Anteiliger Gewinnanteil nachweisen. Bei einfacher Gesellschaft: Gesellschaftsvertrag.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 13, Ziffer 5.3",
    Verification_Status: "verified"
  },

  "163": {
    Canton: "ZH",
    Index: "163",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Übrige Einkünfte",
    Person: "",
    Description: "Taxable capital settlements (40% taxable)",
    Legal_Reference_Canton: "§ 23 lit. d StG ZH",
    Legal_Reference_Federal: "Art. 23 lit. d DBG",
    Rational_Explanation: "Kapitalabfindungen für wiederkehrende Leistungen (z.B. Ablösung von Unterhaltspflichten, Rentenabfindungen) sind zu 40% steuerbar. Dies betrifft einmalige Zahlungen anstelle periodischer Leistungen.",
    Deductibility_Rules: "40% des Kapitalbetrags sind als Einkommen steuerbar. Die restlichen 60% gelten als steuerfreie Vermögensübertragung.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition mit 40%-Regel)",
    Limitations: "Abfindungsvereinbarung oder Gerichtsentscheid erforderlich. Nachweis der Kapitalzahlung. WICHTIG: Nur 40% steuerbar, nicht verwechseln mit Kapitalleistungen aus Vorsorge (Index 510, separater Sondersatz).",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 14, Ziffer 5.4",
    Verification_Status: "verified"
  },

  "164": {
    Canton: "ZH",
    Index: "164",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Übrige Einkünfte",
    Person: "",
    Description: "Other income (miscellaneous taxable income)",
    Legal_Reference_Canton: "§ 23 StG ZH",
    Legal_Reference_Federal: "Art. 23 DBG",
    Rational_Explanation: "Weitere steuerbare Einkünfte, die nicht unter andere Kategorien fallen (z.B. Lotteriegewinne über CHF 1'000, Stipendien, gelegentliche Einkünfte, Finderlohn, Patententschädigungen). Steuerbarkeit je nach Art der Einkunft.",
    Deductibility_Rules: "Je nach Art der Einkunft unterschiedlich steuerbar. Lotteriegewinne: Kantonale Sondersteuer (35% bei Swisslos). Stipendien: meist steuerfrei. Gelegentliche Einkünfte: oft steuerbar.",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, je nach Art unterschiedlich)",
    Limitations: "Belege für die Art der Einkunft erforderlich. Bei Lotteriegewinnen: Gewinnbestätigung. Bei Stipendien: Stipendienverfügung. Bei unklaren Fällen: Rücksprache mit Steuerbehörde empfohlen.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 14, Ziffer 5.5",
    Verification_Status: "verified"
  },

  // Real Estate Income (188)
  "188": {
    Canton: "ZH",
    Index: "188",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Liegenschaften",
    Person: "",
    Description: "Net income from real estate",
    Legal_Reference_Canton: "§ 21 StG ZH",
    Legal_Reference_Federal: "Art. 21 DBG",
    Rational_Explanation: "Nettoertrag aus Liegenschaften ist die Differenz zwischen Mietertrag (oder Eigenmietwert bei selbstgenutztem Wohneigentum) und abziehbaren Liegenschaftskosten (Hypothekarzinsen, Unterhaltskosten, Verwaltungskosten, Versicherungsprämien). Details im Liegenschaftenverzeichnis.",
    Deductibility_Rules: "Steuerbar ist der Nettoertrag (Bruttomietertrag bzw. Eigenmietwert abzüglich Unterhaltskosten und Schuldzinsen). Berechnung erfolgt im Liegenschaftenverzeichnis (Beilage zur Steuererklärung).",
    Max_Deductible: "Nicht zutreffend (Einkommensposition, Nettoprinzip)",
    Limitations: "Liegenschaftenverzeichnis (Formular) vollständig ausfüllen erforderlich. Mietverträge, Hypothekarabrechnungen, Unterhaltsbelege, Versicherungspolice. Bei Eigenmietwert: Amtliche Schätzung der Steuerverwaltung.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 11-12, Ziffer 2 (Liegenschaftenverzeichnis); Merkblatt Eigenmietwert",
    Verification_Status: "verified"
  },

  "199": {
    Canton: "ZH",
    Index: "199",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Total der Einkünfte",
    Person: "",
    Description: "Total income carried forward to income calculation (page 3, line 19)",
    Legal_Reference_Canton: "§ 17-23 StG ZH",
    Legal_Reference_Federal: "Art. 17-23 DBG",
    Rational_Explanation: "Summe aller Einkünfte aus unselbständiger und selbständiger Erwerbstätigkeit, Vorsorge, Wertschriften, Liegenschaften und übrigen Einkünften. Dieser Betrag bildet die Grundlage für die Berechnung des steuerbaren Einkommens.",
    Deductibility_Rules: "System-berechnetes Feld: Summe aller Einkunftsarten. Vollumfänglich steuerbar.",
    Max_Deductible: "Nicht zutreffend (Summationsfeld, kein Abzug)",
    Limitations: "Wird automatisch berechnet als Summe der Ziffern 100-188. Keine separate Dokumentation erforderlich.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Steuererklärung Kanton Zürich 2024, Formular 1 Seite 2",
    Verification_Status: "verified"
  },

  // DEDUCTION INDEXES (200-399)

  // Business Expenses (220, 240)
  "220": {
    Canton: "ZH",
    Index: "220",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Berufsauslagen",
    Person: "Person 1",
    Description: "Business expenses Person 1",
    Legal_Reference_Canton: "§ 26 StG ZH",
    Legal_Reference_Federal: "Art. 26 DBG",
    Rational_Explanation: "Berufsauslagen von unselbständig Erwerbenden sind abziehbar. Kantonal und Bund: Pauschalabzug 3% des Nettolohns (min. CHF 2'000, max. CHF 4'000) oder Effektivabzug (tatsächliche Kosten wie Fahrkosten, Weiterbildung, auswärtige Verpflegung, doppelte Haushaltsführung).",
    Deductibility_Rules: "Wahlrecht zwischen Pauschalabzug (3% Nettolohn, min. CHF 2'000, max. CHF 4'000) oder Effektivabzug. Bei Effektivabzug: Fahrkosten (Arbeitsweg), Mehrkosten auswärtige Verpflegung, Weiterbildung, doppelte Haushaltsführung, Arbeitsmittel.",
    Max_Deductible: "Pauschalabzug: CHF 4'000 (2024). Effektivabzug: keine Begrenzung, jedoch müssen Kosten nachgewiesen und beruflich notwendig sein.",
    Limitations: "Bei Pauschalabzug: Keine Belege erforderlich. Bei Effektivabzug: Nachweise für alle Kosten (Fahrausweise, Kilometerabrechnung, Weiterbildungsrechnungen, Mietbelege bei doppelter Haushaltsführung). WICHTIG: Nur beruflich bedingte Mehrkosten abziehbar.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 16-17, Ziffer 11; Merkblatt Berufsauslagen",
    Verification_Status: "verified"
  },

  "240": {
    Canton: "ZH",
    Index: "240",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Berufsauslagen",
    Person: "Person 2",
    Description: "Business expenses Person 2",
    Legal_Reference_Canton: "§ 26 StG ZH",
    Legal_Reference_Federal: "Art. 26 DBG",
    Rational_Explanation: "Berufsauslagen der zweiten Person von unselbständig Erwerbenden sind abziehbar. Kantonal und Bund: Pauschalabzug 3% des Nettolohns (min. CHF 2'000, max. CHF 4'000) oder Effektivabzug (tatsächliche Kosten wie Fahrkosten, Weiterbildung, auswärtige Verpflegung, doppelte Haushaltsführung).",
    Deductibility_Rules: "Wahlrecht zwischen Pauschalabzug (3% Nettolohn, min. CHF 2'000, max. CHF 4'000) oder Effektivabzug. Bei Effektivabzug: Fahrkosten (Arbeitsweg), Mehrkosten auswärtige Verpflegung, Weiterbildung, doppelte Haushaltsführung, Arbeitsmittel.",
    Max_Deductible: "Pauschalabzug: CHF 4'000 (2024). Effektivabzug: keine Begrenzung, jedoch müssen Kosten nachgewiesen und beruflich notwendig sein.",
    Limitations: "Bei Pauschalabzug: Keine Belege erforderlich. Bei Effektivabzug: Nachweise für alle Kosten (Fahrausweise, Kilometerabrechnung, Weiterbildungsrechnungen, Mietbelege bei doppelter Haushaltsführung). WICHTIG: Nur beruflich bedingte Mehrkosten abziehbar.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 16-17, Ziffer 12; Merkblatt Berufsauslagen",
    Verification_Status: "verified"
  },

  "250": {
    Canton: "ZH",
    Index: "250",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Schuldzinsen",
    Person: "",
    Description: "Debt interest (as far as not already deducted under No. 2)",
    Legal_Reference_Canton: "§ 27 Abs. 1 lit. a StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 1 lit. a DBG",
    Rational_Explanation: "Schuldzinsen auf Privatschulden sind bis zur Höhe des Vermögensertrags plus CHF 50'000 abziehbar. Dies umfasst Hypothekarzinsen auf selbstgenutztem Wohneigentum sowie Zinsen auf Konsumkrediten, Kreditkarten und anderen Privatdarlehen.",
    Deductibility_Rules: "Vollumfänglich abziehbar, soweit nicht bereits unter Ziffer 2 (Liegenschaften) abgezogen. Begrenzung auf Vermögensertrag + CHF 50'000.",
    Max_Deductible: "Max. Vermögensertrag (Ziffer 4 + 5) + CHF 50'000 pro Steuerperiode",
    Limitations: "Zinsabrechnungen der Banken, Hypothekarschuldbriefe, Darlehensverträge erforderlich. Bei selbstgenutztem Wohneigentum separate Deklaration unter Liegenschaftenverzeichnis.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 18-19",
    Verification_Status: "verified"
  },

  "254": {
    Canton: "ZH",
    Index: "254",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Unterhaltsbeiträge",
    Person: "",
    Description: "Alimony to divorced or separated spouse/partner",
    Legal_Reference_Canton: "§ 31 Abs. 1 lit. c StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 1 lit. c DBG",
    Rational_Explanation: "Unterhaltsbeiträge an geschiedene oder getrennt lebende Ehegatten oder eingetragene Partner sind vollumfänglich vom Einkommen abziehbar. Die Beiträge müssen aufgrund eines Gerichtsurteils, Trennungs- oder Scheidungskonvention geleistet werden.",
    Deductibility_Rules: "Vollumfänglich abziehbar bei zahlender Person. Beim Empfänger als Einkommen steuerbar (Ziffer 5.1).",
    Max_Deductible: "Keine Begrenzung (effektiv geleistete Beträge)",
    Limitations: "Scheidungs-/Trennungsurteil, Unterhaltsvereinbarung oder Gerichtsentscheid erforderlich. Nachweis der effektiv geleisteten Zahlungen (Banküberweisungen).",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 19",
    Verification_Status: "verified"
  },

  "255": {
    Canton: "ZH",
    Index: "255",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Unterhaltsbeiträge",
    Person: "",
    Description: "Child maintenance for minor children (until month of majority)",
    Legal_Reference_Canton: "§ 31 Abs. 1 lit. c StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 1 lit. c DBG",
    Rational_Explanation: "Unterhaltsbeiträge für minderjährige Kinder sind bis zum Monat der Volljährigkeit (18. Altersjahr) abziehbar. Dies gilt sowohl für eheliche als auch aussereheliche Kinder, sofern die Unterhaltspflicht besteht.",
    Deductibility_Rules: "Vollumfänglich abziehbar bis zum Monat, in dem das Kind das 18. Lebensjahr vollendet. Beim empfangenden Elternteil als Einkommen des Kindes steuerbar (Ziffer 5.2).",
    Max_Deductible: "Keine Begrenzung (effektiv geleistete Beträge bis Volljährigkeit)",
    Limitations: "Unterhaltsvereinbarung, Gerichtsentscheid oder Vaterschaftsanerkennung erforderlich. Nachweis der Zahlungen und Geburtsurkunden der Kinder.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 19",
    Verification_Status: "verified"
  },

  "256": {
    Canton: "ZH",
    Index: "256",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Unterhaltsbeiträge",
    Person: "",
    Description: "Pension payments - 40% deductible",
    Legal_Reference_Canton: "§ 31 Abs. 1 lit. c StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 1 lit. c DBG",
    Rational_Explanation: "Rentenleistungen aufgrund eines Unterhaltsvertrags sind zu 40% abziehbar. Dies betrifft Rentenvereinbarungen, bei denen anstelle von einmaligen Kapitalzahlungen wiederkehrende Rentenzahlungen geleistet werden.",
    Deductibility_Rules: "40% der geleisteten Rentenzahlungen sind abziehbar. Die restlichen 60% gelten als Kapitalabfindung und sind nicht abziehbar.",
    Max_Deductible: "40% des effektiv geleisteten Rentenbetrags (Feld 2561 × 40%)",
    Limitations: "Rentenvertrag oder Gerichtsentscheid erforderlich. Nachweis der effektiv geleisteten Rentenzahlungen.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 19",
    Verification_Status: "verified"
  },

  "260": {
    Canton: "ZH",
    Index: "260",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Versicherungen und Zinsen",
    Person: "Person 1",
    Description: "Pillar 3a contributions Person 1",
    Legal_Reference_Canton: "§ 30 Abs. 1 lit. b StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 1 lit. d DBG",
    Rational_Explanation: "Beiträge an die Säule 3a (gebundene Selbstvorsorge) sind für Erwerbstätige mit Pensionskasse bis CHF 7'056 und für Selbständige ohne Pensionskasse bis CHF 35'280 (20% des Erwerbseinkommens) abziehbar.",
    Deductibility_Rules: "Vollumfänglich abziehbar innerhalb der gesetzlichen Maximalgrenzen. Nur anerkannte Vorsorgeformen (Bankkonten, Versicherungspolicen) sind abzugsberechtigt.",
    Max_Deductible: "CHF 7'056 (2024) für Arbeitnehmer mit Pensionskasse; CHF 35'280 (2024, max. 20% des Nettoerwerbseinkommens) für Selbständige ohne Pensionskasse",
    Limitations: "Einzahlungsbelege der 3a-Institution erforderlich. Vorsorgevereinbarung mit anerkannter Bank oder Versicherung. Nur bis Erreichen des ordentlichen Rentenalters abziehbar.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 18; Merkblatt Säule 3a 2024",
    Verification_Status: "verified"
  },

  "261": {
    Canton: "ZH",
    Index: "261",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Versicherungen und Zinsen",
    Person: "Person 2",
    Description: "Pillar 3a contributions Person 2",
    Legal_Reference_Canton: "§ 30 Abs. 1 lit. b StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 1 lit. d DBG",
    Rational_Explanation: "Beiträge an die Säule 3a (gebundene Selbstvorsorge) sind für Erwerbstätige mit Pensionskasse bis CHF 7'056 und für Selbständige ohne Pensionskasse bis CHF 35'280 (20% des Erwerbseinkommens) abziehbar.",
    Deductibility_Rules: "Vollumfänglich abziehbar innerhalb der gesetzlichen Maximalgrenzen. Nur anerkannte Vorsorgeformen (Bankkonten, Versicherungspolicen) sind abzugsberechtigt.",
    Max_Deductible: "CHF 7'056 (2024) für Arbeitnehmer mit Pensionskasse; CHF 35'280 (2024, max. 20% des Nettoerwerbseinkommens) für Selbständige ohne Pensionskasse",
    Limitations: "Einzahlungsbelege der 3a-Institution erforderlich. Vorsorgevereinbarung mit anerkannter Bank oder Versicherung. Nur bis Erreichen des ordentlichen Rentenalters abziehbar.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 18; Merkblatt Säule 3a 2024",
    Verification_Status: "verified"
  },

  "270": {
    Canton: "ZH",
    Index: "270",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Versicherungen und Zinsen",
    Person: "",
    Description: "Insurance premiums and interest on savings capital",
    Legal_Reference_Canton: "§ 30 Abs. 1 lit. a StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 1 lit. g DBG",
    Rational_Explanation: "Versicherungsprämien für Lebens-, Kranken-, Unfall- und Haftpflichtversicherungen sowie Zinsen von Sparkapitalien sind abziehbar. Für Alleinstehende max. CHF 3'600 (StG ZH) / CHF 1'700 (DBG), für Verheiratete max. CHF 7'200 (StG ZH) / CHF 3'500 (DBG).",
    Deductibility_Rules: "Pauschalabzug oder Effektivabzug möglich. Bei Effektivabzug: Versicherungsprämien (KVG-Grundversicherung, Zusatzversicherungen, Lebensversicherungen ohne Sparanteil Säule 3b) + Sparzinsen abziehbar.",
    Max_Deductible: "Kantonal (StG ZH): CHF 3'600 Alleinstehende / CHF 7'200 Verheiratete; Bund (DBG): CHF 1'700 Alleinstehende / CHF 3'500 Verheiratete + CHF 700 pro Kind",
    Limitations: "Bei Effektivabzug: Versicherungspolicen, Prämienrechnungen, Sparzinsabrechnungen erforderlich. Nur Schweizer Versicherungen bzw. EU-Versicherungen mit Schweizer Niederlassung.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 18",
    Verification_Status: "verified"
  },

  "280": {
    Canton: "ZH",
    Index: "280",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Versicherungen und Zinsen",
    Person: "",
    Description: "AHV, IV and 2nd pillar contributions (if not already deducted under No. 1 and 2)",
    Legal_Reference_Canton: "§ 30 Abs. 1 lit. b StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 1 lit. d-e DBG",
    Rational_Explanation: "Beiträge an AHV, IV und berufliche Vorsorge (2. Säule) sind abziehbar, sofern sie nicht bereits vom Lohnausweis abgezogen wurden. Dies betrifft vor allem Selbständigerwerbende und freiwillige Einkäufe in die Pensionskasse.",
    Deductibility_Rules: "Vollumfänglich abziehbar. Bei unselbständig Erwerbenden bereits im Lohnausweis abgezogen. Bei Selbständigen separate Deklaration erforderlich.",
    Max_Deductible: "Keine Begrenzung (effektiv geleistete Beiträge gemäss AHV-Abrechnung und Pensionskassenausweis)",
    Limitations: "AHV-Abrechnung und Pensionskassenausweis erforderlich. Bei freiwilligen Einkäufen: Einkaufsbestätigung der Pensionskasse. Sperrfrist von 3 Jahren bei Kapitalbezug nach Einkauf.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 18",
    Verification_Status: "verified"
  },

  "283": {
    Canton: "ZH",
    Index: "283",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Versicherungen und Zinsen",
    Person: "",
    Description: "Costs for management of movable private assets",
    Legal_Reference_Canton: "§ 27 Abs. 1 lit. d StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 1 lit. j DBG",
    Rational_Explanation: "Kosten für die Verwaltung von beweglichem Privatvermögen (Depotgebühren, Vermögensverwaltungskosten, Safe-Miete) sind abziehbar. Dies umfasst effektive Kosten für die professionelle Verwaltung von Wertschriften, Bankkonten und anderen Vermögenswerten.",
    Deductibility_Rules: "Effektivabzug der Verwaltungskosten. Alternativ Pauschalabzug von 3‰ (Promille) des Wertschriftenvermögens möglich.",
    Max_Deductible: "Keine absolute Begrenzung. Pauschalabzug: 3‰ des Wertschriftenvermögens (Ziffer 30.1)",
    Limitations: "Bei Effektivabzug: Rechnungen der Bank, des Vermögensverwalters, Safe-Mietbelege erforderlich. Kosten müssen direkt mit Vermögensverwaltung zusammenhängen.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 19",
    Verification_Status: "verified"
  },

  "284": {
    Canton: "ZH",
    Index: "284",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Spenden",
    Person: "",
    Description: "Other deductions (e.g. political party contributions)",
    Legal_Reference_Canton: "§ 33 Abs. 1 lit. h StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 1 lit. i DBG",
    Rational_Explanation: "Beiträge an politische Parteien sowie Mitgliederbeiträge und Spenden an gemeinnützige Organisationen sind abziehbar. Kantonal bis CHF 10'000, Bund bis 20% des Reineinkommens.",
    Deductibility_Rules: "Abziehbar: Parteibeiträge, Wahlkampfspenden (kantonal bis CHF 10'000 pro Partei). Spenden an gemeinnützige Organisationen separat unter Ziffer 22.2.",
    Max_Deductible: "Kantonal (StG ZH): CHF 10'000 pro politische Partei; Bund (DBG): 20% des Reineinkommens für alle gemeinnützigen Zuwendungen zusammen",
    Limitations: "Spendenbestätigungen der Parteien bzw. gemeinnützigen Organisationen erforderlich. Organisation muss steuerbefreit sein (ESTV-Liste).",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 20",
    Verification_Status: "verified"
  },

  "290": {
    Canton: "ZH",
    Index: "290",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Berufsauslagen",
    Person: "",
    Description: "Special deduction when both spouses/partners are employed",
    Legal_Reference_Canton: "§ 32 StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 2 DBG",
    Rational_Explanation: "Ehepaare, bei denen beide Partner erwerbstätig sind, erhalten einen Zweitverdienerabzug. Kantonal 10% des tieferen Erwerbseinkommens (min. CHF 8'300, max. CHF 13'900), Bund 50% des tieferen Einkommens (max. CHF 13'900).",
    Deductibility_Rules: "Automatisch gewährt bei Erwerbstätigkeit beider Ehegatten. Alternativ: Abzug für erhebliche Mitarbeit im Beruf/Geschäft des anderen Ehegatten.",
    Max_Deductible: "Kantonal: 10% des tieferen Einkommens (min. CHF 8'300, max. CHF 13'900); Bund: 50% des tieferen Einkommens (max. CHF 13'900)",
    Limitations: "Beide Ehegatten müssen erwerbstätig sein. Lohnausweise beider Partner erforderlich. Alternativ Nachweis der erheblichen Mitarbeit.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 20",
    Verification_Status: "verified"
  },

  "292": {
    Canton: "ZH",
    Index: "292",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Weiterbildung",
    Person: "",
    Description: "Occupational education and training costs",
    Legal_Reference_Canton: "§ 30 Abs. 1 lit. c StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 1 lit. j DBG",
    Rational_Explanation: "Berufsorientierte Aus- und Weiterbildungskosten (Kurse, Seminare, Fachliteratur, Prüfungsgebühren) sind abziehbar, sofern sie mit der aktuellen oder zukünftigen Berufstätigkeit zusammenhängen. Kantonal max. CHF 12'000, Bund max. CHF 12'900.",
    Deductibility_Rules: "Abziehbar: Kursgelder, Lehrmittel, Fachliteratur, Prüfungsgebühren. Nicht abziehbar: Allgemeinbildung, Hobby-Kurse, erstmalige Berufsausbildung.",
    Max_Deductible: "Kantonal (StG ZH): CHF 12'000; Bund (DBG): CHF 12'900 ab 2024",
    Limitations: "Kursbestätigungen, Rechnungen, Nachweise der Berufsbezogenheit erforderlich. Muss sich aus der Ausbildungsart ergeben (z.B. MAS, CAS, berufsbegleitendes Studium).",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 19; Merkblatt Aus- und Weiterbildungskosten",
    Verification_Status: "verified"
  },

  "299": {
    Canton: "ZH",
    Index: "299",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Total der Abzüge",
    Person: "",
    Description: "Total deductions carried forward to line 20",
    Legal_Reference_Canton: "§ 26-33 StG ZH",
    Legal_Reference_Federal: "Art. 33 DBG",
    Rational_Explanation: "Summe aller Abzüge (Berufsauslagen, Schuldzinsen, Unterhaltsbeiträge, Vorsorgebeiträge, Versicherungsprämien, Weiterbildungskosten, Kinderbetreuung, etc.). Wird zur Berechnung des Nettoeinkommens vom Gesamteinkommen abgezogen.",
    Deductibility_Rules: "System-berechnetes Feld: Summe aller zulässigen Abzüge gemäss Ziffern 11-17.",
    Max_Deductible: "Keine Begrenzung der Summe (Einzelabzüge haben eigene Maximalgrenzen)",
    Limitations: "Wird automatisch berechnet als Summe der Ziffern 220-290. Keine separate Dokumentation erforderlich.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Steuererklärung Kanton Zürich 2024, Formular 1 Seite 2",
    Verification_Status: "verified"
  },

  "310": {
    Canton: "ZH",
    Index: "310",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Nettoeinkommen",
    Person: "",
    Description: "Net income (Total income minus total deductions)",
    Legal_Reference_Canton: "§ 24 StG ZH",
    Legal_Reference_Federal: "Art. 24 DBG",
    Rational_Explanation: "Nettoeinkommen berechnet als Differenz zwischen Gesamteinkommen (Ziffer 19) und Gesamtabzügen (Ziffer 20). Bildet die Grundlage für zusätzliche Abzüge (Krankheitskosten, Spenden) und Sozialabzüge.",
    Deductibility_Rules: "System-berechnetes Feld: Total Einkünfte (199) minus Total Abzüge (299).",
    Max_Deductible: "Nicht zutreffend (Berechnungsfeld)",
    Limitations: "Automatische Berechnung. Keine separate Dokumentation erforderlich.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Steuererklärung Kanton Zürich 2024, Formular 1 Seite 3",
    Verification_Status: "verified"
  },

  "320": {
    Canton: "ZH",
    Index: "320",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Versicherungen und Zinsen",
    Person: "",
    Description: "Illness and accident costs",
    Legal_Reference_Canton: "§ 33 Abs. 1 lit. e StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 1 lit. h bis DBG",
    Rational_Explanation: "Krankheits- und Unfallkosten sind abziehbar, soweit sie vom Steuerpflichtigen selbst getragen werden und einen Selbstbehalt von 5% des Nettoeinkommens übersteigen (§ 33 Abs. 3 StG ZH). Bundessteuer: Voller Abzug ohne Selbstbehalt.",
    Deductibility_Rules: "Kantonal: Abziehbar sind alle selbst getragenen Kosten abzüglich 5% des Nettoeinkommens. Bund: Voller Abzug ohne Franchise.",
    Max_Deductible: "Keine Begrenzung (effektive Kosten abzüglich Selbstbehalt kantonal, voller Abzug Bund)",
    Limitations: "Arztrechnungen, Spitalrechnungen, Apothekenbelege, Zahnarzt, Brillen, Therapien erforderlich. Nur selbst getragene Kosten (nach Versicherungsleistungen). Franchise und Selbstbehalt der Krankenkasse sind NICHT abziehbar.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 21",
    Verification_Status: "verified"
  },

  "324": {
    Canton: "ZH",
    Index: "324",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Spenden",
    Person: "",
    Description: "Charitable donations",
    Legal_Reference_Canton: "§ 33 Abs. 1 lit. g StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 1 lit. i DBG",
    Rational_Explanation: "Freiwillige Zuwendungen an gemeinnützige Organisationen (Hilfswerke, Kulturinstitutionen, kirchliche Organisationen) sind abziehbar. Kantonal von CHF 100 bis CHF 20'000, Bund bis 20% des Reineinkommens.",
    Deductibility_Rules: "Kantonal: Min. CHF 100, max. CHF 20'000 pro Steuerperiode. Bund: Max. 20% des Reineinkommens (nach Abzug von Ziffer 22.1). Organisation muss steuerbefreit sein.",
    Max_Deductible: "Kantonal: CHF 20'000; Bund: 20% des Reineinkommens nach Krankheitskosten",
    Limitations: "Spendenbestätigungen der Organisationen erforderlich. Organisation muss auf ESTV-Liste der steuerbefreiten Institutionen stehen. Bar-Spenden nicht abzugsfähig (nur Bank/Postüberweisungen).",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 21; ESTV-Liste gemeinnützige Organisationen",
    Verification_Status: "verified"
  },

  "350": {
    Canton: "ZH",
    Index: "350",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Reineinkommen",
    Person: "",
    Description: "Pure income (line 21 minus lines 22.1 and 22.2)",
    Legal_Reference_Canton: "§ 25 StG ZH",
    Legal_Reference_Federal: "Art. 25 DBG",
    Rational_Explanation: "Reineinkommen berechnet als Nettoeinkommen abzüglich Krankheitskosten und gemeinnütziger Zuwendungen. Bildet die Basis für die Berechnung des steuerbaren Einkommens nach Abzug der Sozialabzüge.",
    Deductibility_Rules: "System-berechnetes Feld: Nettoeinkommen (310) minus Krankheitskosten (320) minus Spenden (324).",
    Max_Deductible: "Nicht zutreffend (Berechnungsfeld)",
    Limitations: "Automatische Berechnung. Keine separate Dokumentation erforderlich.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Steuererklärung Kanton Zürich 2024, Formular 1 Seite 3",
    Verification_Status: "verified"
  },

  "365": {
    Canton: "ZH",
    Index: "365",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Ehegattenabzug",
    Person: "",
    Description: "Spouse/partner deduction — / CHF 2'800",
    Legal_Reference_Canton: "§ 35 Abs. 1 lit. d StG ZH",
    Legal_Reference_Federal: "Art. 35 Abs. 1 lit. a DBG",
    Rational_Explanation: "Verheiratete oder in eingetragener Partnerschaft lebende Personen erhalten einen Ehegattenabzug. Kantonal kein Abzug, Bund CHF 2'800 (nur wenn beide Partner erwerbstätig sind, sonst automatisch im Verheiratetentarif berücksichtigt).",
    Deductibility_Rules: "Nur Bundessteuer (DBG): CHF 2'800 wenn beide Ehegatten erwerbstätig sind. Kantonal (StG ZH): Kein separater Abzug, Berücksichtigung durch Verheiratetentarif.",
    Max_Deductible: "Bund: CHF 2'800 (2024); Kanton: CHF 0 (Tarif-Effekt stattdessen)",
    Limitations: "Automatisch bei gemeinsamer Veranlagung. Heiratsurkunde bzw. Partnerschaftsurkunde bei Erstveranlagung.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 22",
    Verification_Status: "verified"
  },

  "370": {
    Canton: "ZH",
    Index: "370",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Kinderabzug",
    Person: "",
    Description: "Child deduction for children in household (CHF 9'300 / CHF 6'700)",
    Legal_Reference_Canton: "§ 35 Abs. 1 lit. a StG ZH",
    Legal_Reference_Federal: "Art. 35 Abs. 1 lit. a DBG",
    Rational_Explanation: "Für jedes minderjährige oder in Ausbildung stehende Kind (bis 25 Jahre) im eigenen Haushalt wird ein Kinderabzug gewährt. Kantonal CHF 9'300, Bund CHF 6'700 pro Kind.",
    Deductibility_Rules: "Pro Kind ein Abzug. Kind muss im Haushalt leben. Bei minderjährigen Kindern automatisch, bei volljährigen Kindern nur bei Ausbildung bis 25. Altersjahr.",
    Max_Deductible: "Pro Kind: Kantonal CHF 9'300, Bund CHF 6'700 (2024)",
    Limitations: "Für minderjährige Kinder: Geburtsurkunde. Für volljährige Kinder in Ausbildung: Lehrvertrag, Studienbestätigung, Schülerbescheinigung. Maximalalter 25 Jahre.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 22",
    Verification_Status: "verified"
  },

  "372": {
    Canton: "ZH",
    Index: "372",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Kinderabzug",
    Person: "",
    Description: "Child deduction for children outside household (CHF 9'300 / CHF 6'700)",
    Legal_Reference_Canton: "§ 35 Abs. 1 lit. a StG ZH",
    Legal_Reference_Federal: "Art. 35 Abs. 1 lit. a DBG",
    Rational_Explanation: "Für jedes minderjährige oder in Ausbildung stehende Kind (bis 25 Jahre) ausserhalb des eigenen Haushalts wird ein Kinderabzug gewährt, sofern Unterhaltspflicht besteht. Kantonal CHF 9'300, Bund CHF 6'700 pro Kind.",
    Deductibility_Rules: "Pro Kind ein Abzug, sofern nicht bereits beim anderen Elternteil geltend gemacht. Bei gemeinsamer elterlicher Sorge Aufteilung möglich. Nur wenn Unterhaltsbeiträge NICHT unter Ziffer 13 abgezogen werden.",
    Max_Deductible: "Pro Kind: Kantonal CHF 9'300, Bund CHF 6'700 (2024)",
    Limitations: "Geburtsurkunde, bei volljährigen Kindern: Ausbildungsnachweis. Nachweis der Unterhaltspflicht. WICHTIG: Entweder Kinderabzug ODER Unterhaltsbeitragsabzug (Ziffer 13.2), nicht beides.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 22",
    Verification_Status: "verified"
  },

  "374": {
    Canton: "ZH",
    Index: "374",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Unterstützungsabzug",
    Person: "",
    Description: "Deduction for supported persons (CHF 2'800 / CHF 6'700)",
    Legal_Reference_Canton: "§ 35 Abs. 1 lit. b StG ZH",
    Legal_Reference_Federal: "Art. 35 Abs. 1 lit. b DBG",
    Rational_Explanation: "Für jede bedürftige Person, die vom Steuerpflichtigen finanziell unterstützt wird (z.B. Eltern, Grosseltern, erwachsene Kinder ohne Einkommen), kann ein Unterstützungsabzug geltend gemacht werden. Kantonal CHF 2'800, Bund CHF 6'700 pro Person.",
    Deductibility_Rules: "Pro unterstützte Person ein Abzug. Person muss bedürftig sein (geringes Einkommen/Vermögen). Unterstützung muss erheblich sein (mind. CHF 2'800 kantonal).",
    Max_Deductible: "Pro Person: Kantonal CHF 2'800, Bund CHF 6'700 (2024)",
    Limitations: "Nachweis der Unterstützungsleistungen (Banküberweisungen, Quittungen). Angaben zu Einkommen und Vermögen der unterstützten Person. Verwandtschaftsverhältnis nachweisen.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 22",
    Verification_Status: "verified"
  },

  "376": {
    Canton: "ZH",
    Index: "376",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Kinderbetreuung",
    Person: "",
    Description: "Deduction for external childcare (birth years 2010-2024) max. CHF 25'000 / CHF 25'500",
    Legal_Reference_Canton: "§ 31 Abs. 1 lit. d StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 3 DBG",
    Rational_Explanation: "Kosten für die Fremdbetreuung von Kindern (Krippe, Tagesmutter, Hort, Mittagstisch) sind abziehbar, sofern beide Elternteile erwerbstätig sind. Kantonal max. CHF 25'000, Bund max. CHF 25'500 pro Kind.",
    Deductibility_Rules: "Abziehbar für Kinder bis 14 Jahre (Jahrgang 2010 oder später). Beide Eltern müssen erwerbstätig sein. Nur Fremdbetreuung durch Dritte (nicht Verwandte).",
    Max_Deductible: "Pro Kind: Kantonal CHF 25'000 (2024), Bund CHF 25'500 (2024). Gilt für Jahrgänge 2010-2024.",
    Limitations: "Rechnungen der Kinderbetreuungseinrichtung erforderlich. Bestätigung der Erwerbstätigkeit beider Eltern. WICHTIG: Betreuung durch Grosseltern, Geschwister etc. NICHT abzugsfähig (nur professionelle Betreuung).",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 20; Merkblatt Kinderbetreuungskosten",
    Verification_Status: "verified"
  },

  "390": {
    Canton: "ZH",
    Index: "390",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Steuerbares Einkommen gesamt (Ziffer 23 abz. Ziff. 24.1 bis 24.3)",
    Person: "",
    Description: "Total taxable income (line 23 minus lines 24.1 to 24.3)",
    Legal_Reference_Canton: "§ 25 StG ZH",
    Legal_Reference_Federal: "Art. 25 DBG",
    Rational_Explanation: "Steuerbares Einkommen berechnet als Reineinkommen abzüglich der Sozialabzüge (Kinderabzüge, Unterstützungsabzüge, Ehegattenabzug). Dies ist die Bemessungsgrundlage für die Steuerberechnung.",
    Deductibility_Rules: "System-berechnetes Feld: Reineinkommen (350) minus Sozialabzüge (365 + 370 + 372 + 374).",
    Max_Deductible: "Nicht zutreffend (Berechnungsfeld)",
    Limitations: "Automatische Berechnung. Keine separate Dokumentation erforderlich.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Steuererklärung Kanton Zürich 2024, Formular 1 Seite 3",
    Verification_Status: "verified"
  },

  "394": {
    Canton: "ZH",
    Index: "394",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Auf steuerbare Einkünfte in anderen Kantonen",
    Person: "",
    Description: "Of which: taxable income in other cantons",
    Legal_Reference_Canton: "§ 83 StG ZH, Art. 127 BV",
    Legal_Reference_Federal: "Art. 91 DBG, Doppelbesteuerungsabkommen Kantone",
    Rational_Explanation: "Bei Wohnsitz in Zürich aber Einkünften aus anderen Kantonen (z.B. Liegenschaftsertrag, Geschäftsbetrieb) erfolgt Steuerausscheidung. Der andere Kanton besteuert anteilig, Zürich rechnet diese Quote von der Gesamtsteuer ab (Vermeidung der Doppelbesteuerung).",
    Deductibility_Rules: "Anteil des steuerbaren Einkommens, der auf anderen Kanton entfällt. Wird für Steuerausscheidungsberechnung verwendet (Interkantonales Steuerausscheidungsverfahren).",
    Max_Deductible: "Nicht zutreffend (Ausscheidungsfeld für Steuerberechnung)",
    Limitations: "Nachweis der Einkunftsquelle im anderen Kanton erforderlich (z.B. Liegenschaftenverzeichnis mit Standort). Steuerveranlagung des anderen Kantons.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 23; Interkantonales Steuerausscheidungsverfahren",
    Verification_Status: "verified"
  },

  "396": {
    Canton: "ZH",
    Index: "396",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Auf steuerbare Einkünfte im Ausland",
    Person: "",
    Description: "Of which: taxable income abroad",
    Legal_Reference_Canton: "§ 6 Abs. 2 StG ZH",
    Legal_Reference_Federal: "Art. 6 DBG, Doppelbesteuerungsabkommen (DBA)",
    Rational_Explanation: "Bei Wohnsitz in der Schweiz sind grundsätzlich weltweite Einkünfte steuerbar. Ausländische Einkünfte werden in der Schweiz angerechnet (Progression svorbe halt oder Steueranrechnung), sofern Doppelbesteuerungsabkommen besteht.",
    Deductibility_Rules: "Anteil des steuerbaren Einkommens aus dem Ausland. Je nach DBA: Progressionsvorbehalt (keine Schweizer Steuer, aber Einbezug in Steuersatz) oder Steueranrechnung (Anrechnung ausländischer Quellensteuer).",
    Max_Deductible: "Nicht zutreffend (Ausscheidungsfeld für Steuerberechnung)",
    Limitations: "Lohnausweis/Einkommensnachweis des ausländischen Arbeitgebers. Quellensteuerbestätigung des Auslands. Angabe des Staates und Art der Einkünfte. Relevant: DBA-Status prüfen.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 23; ESTV-Liste Doppelbesteuerungsabkommen",
    Verification_Status: "verified"
  },

  "398": {
    Canton: "ZH",
    Index: "398",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Steuerbares Einkommen im Kanton Zürich bzw. in der Schweiz",
    Person: "",
    Description: "Taxable income in Canton Zurich / in Switzerland",
    Legal_Reference_Canton: "§ 25 StG ZH",
    Legal_Reference_Federal: "Art. 25 DBG",
    Rational_Explanation: "Steuerbares Einkommen für Kanton Zürich bzw. Bund nach Abzug der interkantonalen/internationalen Ausscheidungsanteile. Dies ist die Bemessungsgrundlage für die effektive Steuerberechnung in Zürich.",
    Deductibility_Rules: "System-berechnetes Feld: Steuerbares Einkommen gesamt (390) minus Einkünfte andere Kantone (394) minus Einkünfte Ausland (396).",
    Max_Deductible: "Nicht zutreffend (Berechnungsfeld)",
    Limitations: "Automatische Berechnung. Keine separate Dokumentation erforderlich. Grundlage für Steuerveranlagung.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Steuererklärung Kanton Zürich 2024, Formular 1 Seite 3",
    Verification_Status: "verified"
  },

  "3160": {
    Canton: "ZH",
    Index: "3160",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Versicherungen und Zinsen",
    Person: "",
    Description: "Disability-related costs",
    Legal_Reference_Canton: "§ 33 Abs. 1 lit. f StG ZH",
    Legal_Reference_Federal: "Art. 33 Abs. 1 lit. h ter DBG",
    Rational_Explanation: "Behinderungsbedingte Kosten (Pflege, Hilfsmittel, Umbaukosten Wohnung/Auto, Mehrkosten Ernährung) sind vollumfänglich abziehbar, wenn eine Behinderung gemäss IVG vorliegt oder Bezug einer Hilflosenentschädigung besteht.",
    Deductibility_Rules: "Vollständiger Abzug ohne Selbstbehalt. Umfasst: Pflege zu Hause, Hilfsmittel (Rollstuhl, Hörgeräte), Umbaukosten, behindertengerechte Fahrzeuge, Mehrkosten für Diäternährung.",
    Max_Deductible: "Keine Begrenzung (voller Abzug der effektiven behinderungsbedingten Kosten)",
    Limitations: "IV-Verfügung oder Hilflosenentschädigung erforderlich. Arztzeugnisse, Rechnungen für Hilfsmittel, Umbaukosten-Nachweise, Pflegekostenbestätigungen. Nur spezifisch behinderungsbedingte Mehrkosten.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 20; Merkblatt Behinderungsbedingte Kosten",
    Verification_Status: "verified"
  },

  // WEALTH INDEXES (400-499)

  "400": {
    Canton: "ZH",
    Index: "400",
    Tax_Year: 2024,
    Main_Category: "Vermögen",
    Sub_Category: "Wertschriften und Guthaben",
    Person: "",
    Description: "Securities and bank balances",
    Legal_Reference_Canton: "§ 38 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 13 Abs. 1 DBG",
    Rational_Explanation: "Wertschriften (Aktien, Obligationen, Fonds, Optionen, Derivate) und Bankguthaben (Spar-, Privat-, Geschäftskonten) sind zum Verkehrswert per 31.12. zu deklarieren. Kurswerte gemäss ESTV-Kursliste oder Bankauszug.",
    Deductibility_Rules: "Steuerpflichtig zum Verkehrswert am Stichtag 31.12. Für kotierte Wertpapiere: ESTV-Kursliste. Für nicht kotierte Wertpapiere: Schätzung gemäss Praxisgrundlagen.",
    Max_Deductible: "Nicht zutreffend (Vermögensposten, kein Abzug)",
    Limitations: "Bankbelege per 31.12., Depotauszüge, ESTV-Kursliste. Für ausländische Wertschriften: Umrechnung zum Tageskurs 31.12. in CHF. Kryptowährungen separat deklarieren.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 24; ESTV-Kursliste 2024",
    Verification_Status: "verified"
  },

  "404": {
    Canton: "ZH",
    Index: "404",
    Tax_Year: 2024,
    Main_Category: "Vermögen",
    Sub_Category: "Bargeld und Edelmetalle",
    Person: "",
    Description: "Cash, gold and other precious metals",
    Legal_Reference_Canton: "§ 38 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 13 Abs. 1 DBG",
    Rational_Explanation: "Bargeld (Banknoten, Münzen im Safe oder zu Hause), physisches Gold (Barren, Münzen) und andere Edelmetalle (Silber, Platin) sind zum Verkehrswert per 31.12. zu deklarieren.",
    Deductibility_Rules: "Steuerpflichtig zum Verkehrswert 31.12. Für Gold: Goldpreis × Gewicht in kg. Für Bargeld: Nominalwert.",
    Max_Deductible: "Nicht zutreffend (Vermögensposten, kein Abzug)",
    Limitations: "Nachweis des Bestands erforderlich (Quittungen, Kaufbelege). Für Gold: Gewichtsnachweis, Feingehalt. Lagerort angeben (Safe, zu Hause, Bankschliessfach).",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 24",
    Verification_Status: "verified"
  },

  "406": {
    Canton: "ZH",
    Index: "406",
    Tax_Year: 2024,
    Main_Category: "Vermögen",
    Sub_Category: "Versicherungen",
    Person: "",
    Description: "Life and pension insurances (taxable value per insurance certificate) Total",
    Legal_Reference_Canton: "§ 38 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 13 Abs. 1 DBG",
    Rational_Explanation: "Rückkaufswert von Lebens- und Rentenversicherungen (Säule 3b) gemäss Bescheinigung der Versicherungsgesellschaft per 31.12. Kapitalversicherungen mit Sparanteil sind vermögenssteuerpflichtig.",
    Deductibility_Rules: "Steuerpflichtig zum Rückkaufswert gemäss Police. Risikoversicherungen (ohne Sparanteil) sind NICHT vermögenssteuerpflichtig.",
    Max_Deductible: "Nicht zutreffend (Vermögensposten, kein Abzug)",
    Limitations: "Versicherungspolice mit Rückkaufswertbestätigung per 31.12. erforderlich. Nur Policen mit Sparanteil (Kapitalversicherungen). Reine Risikoversicherungen nicht deklarieren.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 24",
    Verification_Status: "verified"
  },

  "412": {
    Canton: "ZH",
    Index: "412",
    Tax_Year: 2024,
    Main_Category: "Vermögen",
    Sub_Category: "Fahrzeuge",
    Person: "",
    Description: "Motor vehicles: Purchase price: Year: (Purchase year)",
    Legal_Reference_Canton: "§ 39 Abs. 2 lit. e StG ZH",
    Legal_Reference_Federal: "Art. 13 Abs. 2 lit. d DBG",
    Rational_Explanation: "Motorfahrzeuge (Autos, Motorräder, Boote) werden zum Kaufpreis abzüglich jährlicher Wertminderung von 20-40% besteuert (je nach Fahrzeugtyp und Alter). Nach ca. 5 Jahren Restwert CHF 0.",
    Deductibility_Rules: "Steuerpflichtig zum geschätzten Verkehrswert. Abschreibung pro Jahr: ca. 20-40% vom Kaufpreis. Nach 5-8 Jahren meist vollständig abgeschrieben (Restwert CHF 0).",
    Max_Deductible: "Nicht zutreffend (Vermögensposten, kein Abzug)",
    Limitations: "Fahrzeugausweis, Kaufvertrag mit Kaufpreis und Kaufjahr. Leasingfahrzeuge gehören dem Leasinggeber (nicht deklarieren). Geschäftsfahrzeuge bei Selbständigen im Geschäftsvermögen (Ziffer 32).",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 25",
    Verification_Status: "verified"
  },

  "414": {
    Canton: "ZH",
    Index: "414",
    Tax_Year: 2024,
    Main_Category: "Vermögen",
    Sub_Category: "Beteiligungen",
    Person: "",
    Description: "Business/corporate shares",
    Legal_Reference_Canton: "§ 38 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 13 Abs. 1 DBG",
    Rational_Explanation: "Anteile an nicht kotierten Unternehmen (GmbH, AG) werden nach Bewertungsmethoden der ESTV bewertet (Substanzwert + Ertragswert). Für KMU oft Schätzung aufgrund Jahresabschluss.",
    Deductibility_Rules: "Steuerpflichtig zum Verkehrswert. Bewertung gemäss ESTV-Kreisschreiben Nr. 28 (Anteilsbewertung). Für kotierte Aktien: ESTV-Kursliste.",
    Max_Deductible: "Nicht zutreffend (Vermögensposten, kein Abzug)",
    Limitations: "Aktienregisterauszug, Gesellschaftsvertrag, Jahresabschluss des Unternehmens. Bei nicht kotierten Unternehmen: Bewertungsnachweis gemäss ESTV-Methode.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 25; ESTV-Kreisschreiben Nr. 28",
    Verification_Status: "verified"
  },

  "416": {
    Canton: "ZH",
    Index: "416",
    Tax_Year: 2024,
    Main_Category: "Vermögen",
    Sub_Category: "Übrige Vermögenswerte",
    Person: "",
    Description: "Other assets; detailed description:",
    Legal_Reference_Canton: "§ 38 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 13 Abs. 1 DBG",
    Rational_Explanation: "Weitere Vermögenswerte wie Kunstgegenstände, Antiquitäten, Sammlungen, Schmuck, Uhren, Kryptowährungen. Abzüglich Freibetrag für Hausrat (CHF 50'000-100'000 je nach Kanton).",
    Deductibility_Rules: "Steuerpflichtig zum Verkehrswert. Hausrat und persönliche Gebrauchsgegenstände sind bis CHF 50'000-100'000 steuerfrei (Freibetrag kantonal unterschiedlich). Darüber hinausgehende Werte sind steuerbar.",
    Max_Deductible: "Nicht zutreffend (Vermögensposten, kein Abzug)",
    Limitations: "Schätzung oder Kaufbelege für wertvolle Gegenstände. Für Kryptowährungen: Wallet-Auszug per 31.12., Umrechnung zum Tageskurs. Für Kunst/Antiquitäten: Expertenschätzung bei hohen Werten.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 25",
    Verification_Status: "verified"
  },

  "421": {
    Canton: "ZH",
    Index: "421",
    Tax_Year: 2024,
    Main_Category: "Vermögen",
    Sub_Category: "Immobilien",
    Person: "",
    Description: "Taxed at market value",
    Legal_Reference_Canton: "§ 39 Abs. 1 StG ZH",
    Legal_Reference_Federal: "Art. 14 Abs. 1 DBG",
    Rational_Explanation: "Liegenschaften (Grundstücke, Wohnungen, Häuser) werden zum Verkehrswert (Marktwert) besteuert. Zürich verwendet den amtlichen Wert (Steuerwert gemäss Veranlagungsbehörde).",
    Deductibility_Rules: "Steuerpflichtig zum amtlichen Wert (ca. 70-90% des Marktwerts). Bundessteuer: Verkehrswert gemäss Schätzung. Abzüglich Hypothekarschulden (Ziffer 34).",
    Max_Deductible: "Nicht zutreffend (Vermögensposten, kein Abzug)",
    Limitations: "Liegenschaftenverzeichnis ausfüllen (Beilage zur Steuererklärung). Grundbuchauszug, Kaufvertrag, Hypothekarurkunde. Amtlicher Wert wird von Steuerbehörde festgelegt.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 25; Beilage Liegenschaftenverzeichnis",
    Verification_Status: "verified"
  },

  "422": {
    Canton: "ZH",
    Index: "422",
    Tax_Year: 2024,
    Main_Category: "Vermögen",
    Sub_Category: "Immobilien",
    Person: "",
    Description: "Taxed at income value (agriculture or forestry)",
    Legal_Reference_Canton: "§ 39 Abs. 3 StG ZH",
    Legal_Reference_Federal: "Art. 14 Abs. 2 DBG",
    Rational_Explanation: "Land- und forstwirtschaftlich genutzte Grundstücke werden nicht zum Verkehrswert, sondern zum Ertragswert (kapitalisierter Ertrag) besteuert. Dies führt zu deutlich tieferen Steuerwerten.",
    Deductibility_Rules: "Steuerpflichtig zum Ertragswert (Kapitalisierung des durchschnittlichen Jahresertrags). Berechnung gemäss kantonaler Bewertungspraxis für Landwirtschaftsland.",
    Max_Deductible: "Nicht zutreffend (Vermögensposten, kein Abzug)",
    Limitations: "Nachweis der land-/forstwirtschaftlichen Nutzung erforderlich. Pachtverträge, Betriebsdaten, Ertragsnachweise. Amtliche Bewertung durch Steuerbehörde.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 26; Merkblatt Landwirtschaftsvermögen",
    Verification_Status: "verified"
  },

  "430": {
    Canton: "ZH",
    Index: "430",
    Tax_Year: 2024,
    Main_Category: "Vermögen",
    Sub_Category: "Geschäftsvermögen",
    Person: "",
    Description: "Equity of self-employed without business securities",
    Legal_Reference_Canton: "§ 40 StG ZH",
    Legal_Reference_Federal: "Art. 18 Abs. 2 DBG",
    Rational_Explanation: "Eigenkapital von Einzelfirmen und Personengesellschaften (ohne Wertschriften im Geschäftsvermögen) wird als Geschäftsvermögen deklariert. Berechnung: Aktiven minus Passiven gemäss Geschäftsbilanz.",
    Deductibility_Rules: "Steuerpflichtig zum Eigenkapitalwert gemäss Geschäftsbilanz per 31.12. Geschäftswertschriften werden separat unter Ziffer 30.1 deklariert.",
    Max_Deductible: "Nicht zutreffend (Vermögensposten, kein Abzug)",
    Limitations: "Geschäftsbilanz per 31.12. erforderlich. Hilfsblatt A (Gewinnermittlung) ausfüllen. Jahresabschluss mit Aktiven- und Passivenverzeichnis.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 26; Hilfsblatt A",
    Verification_Status: "verified"
  },

  "460": {
    Canton: "ZH",
    Index: "460",
    Tax_Year: 2024,
    Main_Category: "Vermögen",
    Sub_Category: "Total Vermögen",
    Person: "",
    Description: "Total assets",
    Legal_Reference_Canton: "§ 38-40 StG ZH",
    Legal_Reference_Federal: "Art. 13-18 DBG",
    Rational_Explanation: "Summe aller Vermögenswerte (Wertschriften, Bargeld, Versicherungen, Fahrzeuge, Beteiligungen, Liegenschaften, Geschäftsvermögen, übrige Vermögenswerte). Bildet die Grundlage für die Vermögenssteuer abzüglich Schulden.",
    Deductibility_Rules: "System-berechnetes Feld: Summe aller Vermögensposten Ziffer 30-32.",
    Max_Deductible: "Nicht zutreffend (Summationsfeld)",
    Limitations: "Automatische Berechnung. Keine separate Dokumentation erforderlich.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Steuererklärung Kanton Zürich 2024, Formular 1 Seite 4",
    Verification_Status: "verified"
  },

  "470": {
    Canton: "ZH",
    Index: "470",
    Tax_Year: 2024,
    Main_Category: "Schulden",
    Sub_Category: "Schulden",
    Person: "",
    Description: "Debts",
    Legal_Reference_Canton: "§ 41 StG ZH",
    Legal_Reference_Federal: "Art. 20 DBG",
    Rational_Explanation: "Schulden (Hypotheken, Kredite, Kreditkarten, Kontokorrent, Privatdarlehen, Steuerschulden) sind per 31.12. vom Vermögen abziehbar. Nur effektive, nachgewiesene Schulden sind abzugsfähig.",
    Deductibility_Rules: "Vollumfänglich vom Reinvermögen abziehbar. Hypothekarschulden, Bankkredite, Kreditkarten, Steuerschulden, Privatdarlehen. Saldo per 31.12. massgebend.",
    Max_Deductible: "Keine Begrenzung (effektive Schulden per 31.12.)",
    Limitations: "Hypothekarurkunden, Kreditverträge, Kontoauszüge per 31.12., Kreditkartenabrechnungen, Schuldbriefe, Darlehensverträge. WICHTIG: Nur nachgewiesene Schulden sind abzugsfähig.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 26",
    Verification_Status: "verified"
  },

  "490": {
    Canton: "ZH",
    Index: "490",
    Tax_Year: 2024,
    Main_Category: "Vermögen",
    Sub_Category: "Steuerbares Vermögen",
    Person: "",
    Description: "Total taxable wealth",
    Legal_Reference_Canton: "§ 42 StG ZH",
    Legal_Reference_Federal: "Art. 13-20 DBG (Keine Vermögenssteuer Bund)",
    Rational_Explanation: "Steuerbares Vermögen berechnet als Total Vermögen (460) abzüglich Schulden (470). Dies ist die Bemessungsgrundlage für die Vermögenssteuer (nur Kantone und Gemeinden, nicht Bund).",
    Deductibility_Rules: "System-berechnetes Feld: Total Vermögen (460) minus Total Schulden (470). Bund erhebt KEINE Vermögenssteuer (nur Kantone/Gemeinden).",
    Max_Deductible: "Nicht zutreffend (Berechnungsfeld)",
    Limitations: "Automatische Berechnung. Keine separate Dokumentation erforderlich. Freibeträge kantonal unterschiedlich (ZH: keine Freibeträge, Steuer ab CHF 1.-).",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Steuererklärung Kanton Zürich 2024, Formular 1 Seite 4",
    Verification_Status: "verified"
  },

  "494": {
    Canton: "ZH",
    Index: "494",
    Tax_Year: 2024,
    Main_Category: "Vermögen",
    Sub_Category: "Auf steuerbare Vermögenswerte in anderen Kantonen",
    Person: "",
    Description: "Of which: taxable assets in other cantons",
    Legal_Reference_Canton: "§ 89 StG ZH, Art. 127 BV",
    Legal_Reference_Federal: "Art. 93 DBG (keine Bundesvermögenssteuer), Interkantonale Steuerausscheidung",
    Rational_Explanation: "Vermögenswerte in anderen Kantonen (Liegenschaften, Geschäftsbetriebe) werden für Steuerausscheidung separat erfasst. Der Standortkanton besteuert anteilig, Wohnsitzkanton ZH rechnet Quote ab.",
    Deductibility_Rules: "Anteil des steuerbaren Vermögens in anderen Kantonen. Wird für interkantonale Steuerausscheidung verwendet. Nur relevant für Vermögenssteuer (nicht Bund).",
    Max_Deductible: "Nicht zutreffend (Ausscheidungsfeld)",
    Limitations: "Nachweis des Vermögensobjekts im anderen Kanton (Grundbuchauszug, Geschäftsbetriebsnachweis). Steuerveranlagung des Standortkantons.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 27; Interkantonale Steuerausscheidung",
    Verification_Status: "verified"
  },

  "496": {
    Canton: "ZH",
    Index: "496",
    Tax_Year: 2024,
    Main_Category: "Vermögen",
    Sub_Category: "Auf steuerbare Vermögenswerte im Ausland",
    Person: "",
    Description: "Of which: taxable assets abroad",
    Legal_Reference_Canton: "§ 6 Abs. 3 StG ZH",
    Legal_Reference_Federal: "Art. 93 DBG (keine Bundesvermögenssteuer), DBA",
    Rational_Explanation: "Vermögenswerte im Ausland (Liegenschaften, Bankkonten, Wertschriften) werden für Steuerausscheidung separat erfasst. Je nach DBA: Freistellung oder Steueranrechnung. Oft Progressionsvorbehalt.",
    Deductibility_Rules: "Anteil des steuerbaren Vermögens im Ausland. Je nach DBA: Freistellung (nur Progressionsvorbehalt) oder Steueranrechnung (Anrechnung ausländischer Vermögenssteuer).",
    Max_Deductible: "Nicht zutreffend (Ausscheidungsfeld)",
    Limitations: "Nachweis der ausländischen Vermögenswerte (Bankauszüge, Grundbuchauszüge, Depotbestätigungen). Umrechnung in CHF zum Kurs 31.12. Angabe des Staates.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 27; ESTV-Liste DBA",
    Verification_Status: "verified"
  },

  "498": {
    Canton: "ZH",
    Index: "498",
    Tax_Year: 2024,
    Main_Category: "Vermögen",
    Sub_Category: "Steuerbares Vermögen im Kanton Zürich",
    Person: "",
    Description: "Taxable wealth in Canton Zurich",
    Legal_Reference_Canton: "§ 42 StG ZH",
    Legal_Reference_Federal: "Nicht anwendbar (keine Bundesvermögenssteuer)",
    Rational_Explanation: "Steuerbares Vermögen für Kanton Zürich nach Abzug der interkantonalen/internationalen Ausscheidungsanteile. Dies ist die Bemessungsgrundlage für die Vermögenssteuer in Zürich.",
    Deductibility_Rules: "System-berechnetes Feld: Steuerbares Vermögen gesamt (490) minus Vermögen andere Kantone (494) minus Vermögen Ausland (496).",
    Max_Deductible: "Nicht zutreffend (Berechnungsfeld)",
    Limitations: "Automatische Berechnung. Grundlage für Vermögenssteuerveranlagung Kanton und Gemeinde Zürich.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Steuererklärung Kanton Zürich 2024, Formular 1 Seite 4",
    Verification_Status: "verified"
  },

  "9020": {
    Canton: "ZH",
    Index: "9020",
    Tax_Year: 2024,
    Main_Category: "Vermögen",
    Sub_Category: "Immobilien",
    Person: "",
    Description: "Real estate (general category for properties)",
    Legal_Reference_Canton: "§ 39 StG ZH",
    Legal_Reference_Federal: "Art. 14 DBG",
    Rational_Explanation: "Sammelkategorie für alle Liegenschaften (Grundstücke, Wohnungen, Häuser). Details werden im Liegenschaftenverzeichnis (Beilage) erfasst. Bewertung zum Verkehrswert (421) oder Ertragswert (422).",
    Deductibility_Rules: "Steuerpflichtig zum amtlichen Wert gemäss Veranlagungsbehörde. Details im Liegenschaftenverzeichnis erfassen.",
    Max_Deductible: "Nicht zutreffend (Vermögensposten, kein Abzug)",
    Limitations: "Liegenschaftenverzeichnis ausfüllen. Grundbuchauszug, Kaufvertrag, Hypothekarurkunde erforderlich.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Steuererklärung Kanton Zürich 2024, Beilage Liegenschaftenverzeichnis",
    Verification_Status: "verified"
  },

  // SPECIAL CATEGORIES (500-519)

  "510": {
    Canton: "ZH",
    Index: "510",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Kapitalleistungen",
    Person: "",
    Description: "Capital payments from AHV/IV, vested benefits, 2nd pillar, 3a pillar, death/disability benefits",
    Legal_Reference_Canton: "§ 39 lit. b StG ZH, § 46 StG ZH (Spezialbesteuerung)",
    Legal_Reference_Federal: "Art. 22 Abs. 2 DBG, Art. 38 DBG (Spezialbesteuerung)",
    Rational_Explanation: "Kapitalleistungen aus Vorsorge (Pensionskasse, Säule 3a, Freizügigkeitspolice) werden separat zum privilegierten Sondersatz besteuert (ca. 5-8% je nach Kanton). NICHT zum normalen Einkommenssatz addiert.",
    Deductibility_Rules: "Separate Besteuerung zum Spezial-Tarif (privilegierte Besteuerung). Wird NICHT zum übrigen Einkommen addiert. Je nach Höhe: progressiver Sondersatz.",
    Max_Deductible: "Nicht zutreffend (separate Steuerberechnung, keine Limitation)",
    Limitations: "Bescheinigung der Pensionskasse, Freizügigkeitseinrichtung oder 3a-Bank erforderlich. Formular 'Kapitalleistungen aus Vorsorge' ausfüllen. Datum und Grund der Auszahlung angeben.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/steuererklarung.html",
    Source_Document: "Wegleitung zur Steuererklärung 2024 Kanton Zürich, Seite 29; Merkblatt Kapitalleistungen aus Vorsorge",
    Verification_Status: "verified"
  },

  "516": {
    Canton: "ZH",
    Index: "516",
    Tax_Year: 2024,
    Main_Category: "Einkommen",
    Sub_Category: "Schenkungen erhalten",
    Person: "",
    Description: "Gifts received: Date [Box] 2024 from [Box] Value:",
    Legal_Reference_Canton: "§ 12 StG ZH (Schenkungssteuer)",
    Legal_Reference_Federal: "Nicht steuerbar bei DBG (keine Erbschafts-/Schenkungssteuer Bund)",
    Rational_Explanation: "Erhaltene Schenkungen unterliegen der kantonalen Schenkungssteuer (nicht Einkommenssteuer). Freibeträge je nach Verwandtschaftsgrad. Kanton Zürich: Direkte Nachkommen steuerfrei, übrige je nach Betrag und Verwandtschaft.",
    Deductibility_Rules: "Keine Einkommenssteuer, aber separate Schenkungssteuer. Freibeträge ZH: Ehegatten/Kinder steuerfrei, Eltern/Geschwister ab CHF 50'000, übrige Personen ab CHF 5'000.",
    Max_Deductible: "Nicht zutreffend (separate Schenkungssteuer, nicht Einkommenssteuer)",
    Limitations: "Schenkungsvertrag, Nachweis der Schenkung (Banküberweisungen, Eigentumsübertragung). Datum, Schenker, Wert angeben. Bei Liegenschaften: Grundbuchauszug.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/erbschaftssteuer-schenkungssteuer.html",
    Source_Document: "Merkblatt Schenkungssteuer Kanton Zürich 2024",
    Verification_Status: "verified"
  },

  "519": {
    Canton: "ZH",
    Index: "519",
    Tax_Year: 2024,
    Main_Category: "Abzüge",
    Sub_Category: "Schenkungen ausgerichtet",
    Person: "",
    Description: "Gifts given: Date [Box] 2024 to [Box] Value:",
    Legal_Reference_Canton: "§ 12 StG ZH (Schenkungssteuer beim Empfänger)",
    Legal_Reference_Federal: "Nicht steuerbar bei DBG (keine Erbschafts-/Schenkungssteuer Bund)",
    Rational_Explanation: "Ausgerichtete Schenkungen sind beim Schenker NICHT abziehbar (ausser gemeinnützige Zuwendungen unter Ziffer 22.2/16.5). Schenkungssteuer zahlt der Empfänger, nicht der Schenker.",
    Deductibility_Rules: "NICHT abziehbar beim Schenker. Nur Deklarationspflicht für Schenkungssteuer beim Empfänger. Ausnahme: Spenden an gemeinnützige Organisationen (separat unter Ziffer 284/324).",
    Max_Deductible: "Nicht abziehbar (nur Deklaration für Schenkungssteuer Empfänger)",
    Limitations: "Schenkungsvertrag, Nachweis der Schenkung. Datum, Empfänger, Wert angeben. Bei Liegenschaften: Grundbuchauszug. WICHTIG: Keine Abzugswirkung beim Schenker.",
    Source: "https://www.zh.ch/de/steuern-finanzen/steuern/erbschaftssteuer-schenkungssteuer.html",
    Source_Document: "Merkblatt Schenkungssteuer Kanton Zürich 2024",
    Verification_Status: "verified"
  }
};

module.exports = legalMetadata;
