#!/bin/bash

# Direct check using Firebase console URL
PROJECT_ID="taxedgmbh"
DATABASE="taxedgmbh"
WORKSPACE_ID="V59XKFt4De8ooBKlAULx"

echo "🔍 FIRESTORE WORKSPACE QUERY"
echo "=============================="
echo ""
echo "Project: $PROJECT_ID"
echo "Database: $DATABASE"
echo "Workspace ID: $WORKSPACE_ID"
echo ""
echo "📋 Please manually check in Firebase Console:"
echo "   https://console.firebase.google.com/project/$PROJECT_ID/firestore/databases/$DATABASE/data/workspaces/$WORKSPACE_ID"
echo ""
echo "🔎 What to look for:"
echo "   1. Does the workspace document exist?"
echo "   2. Check the 'memberIds' field - what values are in the array?"
echo "   3. Check the 'members' field - what user IDs are listed?"
echo "   4. Check the 'ownerId' field - what is the owner's user ID?"
echo ""
echo "🆔 Also check the authenticated user ID in the app:"
echo "   - Look for console logs containing 'User ID:'"
echo "   - Or check Firebase Authentication console for the test user's UID"
echo ""
